config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,  controllers: {
    confirmations: 'confirmations', 
    invitations: 'invitations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 
  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  root to: "home#index"
  
  
  resources :users do
    resources :companies
    resources :associates
    resources :accounts
  end
  
  resources :positions
  resources :companies do
    resources :associates, only: [:index, :show]
    resources :accounts, only: [:index, :show]
  end
  
  resources :associates do 
    resources :accounts, only: [:index, :show]
  end  
  
  resources :packages do
    resources :package_comments
  end
  
  resources :package_comments 
  
  resources :accounts do
    resources :packages
  end
  post "accounts/new", to: "accounts#create"
  
  
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  layout "dashboard"
  def new
  @route_path = user_invitation_path
  @title = "Add New Associate:"
  @subject = User.new
  
    p = @subject.positions.build
    p.build_company
    
 
  end

  def index
    @role = associates_params[:role]
    @associates = current_user.specified_associates(rle: @role)
    @tiling_elements = @associates
    @column_headings = current_user.company_names
    @title = "#{current_user.name}'s Associates"
    
  end
  
  def show
    @associate = User.find(associates_params[:id])
    if associates_params[:company_id]
      @company = Company.find(associates_params[:company_id])
    end
  end
  
  private

  def associates_params
    params.permit(:role, :id, :user_id, :company_id)  
  end  
end

app/helpers/associates_helper.rb
module AssociatesHelper

  def associates_sidebar_menu
    content_tag(:div, class: "mt-2") do
      current_user.class.roles.keys.each do |role| 
       concat associates_link(role)
      end
      concat new_associate if current_user.admin? 
    end  
  end
  
  def associates_link(var)
    link_to user_associates_path(current_user.id, {:role => var}), class: "flex justify-between item-center px-3 py-1 text-sm font-medium text-gray-700 rounded-lg hover:bg-gray-200" do
      associate_title(var) + associate_count(var)  
    end
  end

  def associate_title(role)
   tag.span role.titleize.pluralize, class: ["text-xs", "font-semibold", "text-gray-700"] 
  end
  
  def associate_count(role)
   tag.span current_user.specified_associates(rle: role).count, class: ["text-xs", "font-semibold", "text-gray-700"] 
  end

  def new_associate
    content_tag(:button, class: "mt-3 py-2 px-3 flex items-center text-sm font-medium text-gray-600 border border-gray-300 rounded hover:bg-gray-200") do 
      cross + 
      add_associate_link 
    end
  end

  def add_associate_link  
    content_tag(:span, class: "ml-2") do
      concat link_to "New Associate", new_user_associate_path(current_user.id)
    end
  end
    

end

app/views/associates/highlight/_associate_indexes.html.erb
<%# passed to "users/highlight/main_display" via "content_for :main_panel" in view files %>
<%# renders collection of current_user.packages by passing "user/highlight/package" collection partial %>

  <%# byebug %>  

<main class="p-3 inline-flex" id="userr_reference_point">
  <% @associate.accounts.each do |account| %>
   <%a;sldkjf;lkj%>
    <div class="flex-shrink-0 ml-3 w-80 mt-2 p-3 bg-gray-100 rounded">
      <h3 clas="text-sm font-medium text-gray-900"><%= cattegory[:role].titleize.pluralize %></h3>
      <ul class="mt-2">
        <li class="mt-3">                  
          <%= render partial: 'associates/highlight/associate_profiles', locals: {:sorted_associates => current_user.associated_users(category[:role])} %>   
        </li>            
      </ul>
    </div>
  <% end %>  
</main>

app/views/associates/highlight/_associate_tile.html.erb
<li class="mt-3" id="single tile">

<% if @company %>
<%# build out company_package_path for package tiles to be linked to!!!%>
  <%= link_to  company_associate_path(@company.id, associate.id), :class=>"block p-5 bg-white rounded-lg shadow"  do %>
  
    <div class="flex justify-between items-center py-2">     
      <h2 class="text-sm font-medium font-bold text-gray-900"><%= associate.name.upcase %></h2>
    </div>

    <div class="flex justify-between">
      <% if associate.comments.count == 1%>
        <p class="text-sm font-medium text-gray-900 leading-snug"> <%= associate.comments.first.content %></p>
      <% else %>
      <ul>
        <% associate.comments.each do |comment|  %>
        <li>
          <p class="text-sm font-medium text-gray-900 leading-snug"><%= comment.content %></p>
        </li>
        <% end%>
      </ul>
      <% end%>
    </div>

    <div class="flex mt-2 justify-between items-baseline">
      <div class="text-sm text-gray-600">
        <p class="text-sm text-gray-600"> <%= associate.positions.first.title %></p>
      </div>
      
      <div>
        <span class="px-2 inline-flex items-center bg-teal-100 rounded">
          <svg class="h-2 w-2 text-teal-500" viewBox="0 0 8 8" fill="currentColor">
          <circle cx="4" cy="4" r="3" />
          </svg>
          <span class="ml-1 py-1 text-sm font-medium leading-tight text-teal-900"><%= associate.username %></span>
        </span>
      </div>
    </div>
  <% end %>
<% else %>
  <%= link_to  user_associate_path(current_user.id, associate.id), :class=>"block p-5 bg-white rounded-lg shadow"  do %>
<% end %>

    <div class="flex justify-between items-center py-2">     
      <h2 class="text-sm font-medium font-bold text-gray-900"><%= associate.name.upcase %></h2>
      <span class="-ml-2 rounded-full border-2 border-white">
        <img class="h-12 w-12 rounded-full object-cover" src="<%= associate.url %>" alt="profile photo">
      </span>
    </div>

    <div class="flex justify-between">
    <%a;sldkjf;lkj%>
      <% if associate.companies.count == 1%>
        <p class="text-sm font-medium text-gray-900 leading-snug"> <%= associate.companies.first.name %></p>
      <% else %>
      <ul>
        <% associate.companies.each do |company|  %>
        <li>
          <p class="text-sm font-medium text-gray-900 leading-snug"><%= company.name %></p>
        </li>
        <% end%>
      </ul>
      <% end%>
    </div>

    <div class="flex mt-2 justify-between items-baseline">
      <div class="text-sm text-gray-600">
        <p class="text-sm text-gray-600"> <%= associate.positions.first.title %></p>
      </div>

      <div>
        <span class="px-2 inline-flex items-center bg-teal-100 rounded">
          <svg class="h-2 w-2 text-teal-500" viewBox="0 0 8 8" fill="currentColor">
          <circle cx="4" cy="4" r="3" />
          </svg>
          <span class="ml-1 py-1 text-sm font-medium leading-tight text-teal-900"><%= associate.username %></span>
        </span>
      </div>
    </div>
  <% end %>
</li>

app/views/associates/highlight/_tile.html copy.erb
<h1 class="text-xs" id="iddd">associates/highlight/tile_copy</h1>
<h1>this is the page!</h1>

<li class="mt-3" id="single tile">

<% if @company %>
<%# build out company_package_path for package tiles to be linked to!!!%>
  <%= link_to  company_associate_path(@company.id, associate.id), :class=>"block p-5 bg-white rounded-lg shadow"  do %>
  
    <div class="flex justify-between items-center py-2">     
      <h2 class="text-sm font-medium font-bold text-gray-900"><%= associate.name.upcase %></h2>
    </div>

    <div class="flex justify-between">
      <% if associate.companies.count == 1%>
        <p class="text-sm font-medium text-gray-900 leading-snug"> <%= associate.companies.first.name %></p>
      <% else %>
      <ul>
        <% associate.companies.each do |company|  %>
        <li>
          <p class="text-sm font-medium text-gray-900 leading-snug"><%= company.name %></p>
        </li>
        <% end%>
      </ul>
      <% end%>
    </div>

    <div class="flex mt-2 justify-between items-baseline">
      <div class="text-sm text-gray-600">
        <p class="text-sm text-gray-600"> <%= associate.positions.first.title %></p>
      </div>
      
      <div>
        <span class="px-2 inline-flex items-center bg-teal-100 rounded">
          <svg class="h-2 w-2 text-teal-500" viewBox="0 0 8 8" fill="currentColor">
          <circle cx="4" cy="4" r="3" />
          </svg>
          <span class="ml-1 py-1 text-sm font-medium leading-tight text-teal-900"><%= associate.username %></span>
        </span>
      </div>
    </div>
  <% end %>
<% else %>
  <%= link_to  user_associate_path(current_user.id, associate.id), :class=>"block p-5 bg-white rounded-lg shadow"  do %>


    <div class="flex justify-between items-center py-2">     
      <h2 class="text-sm font-medium font-bold text-gray-900"><%= associate.name.upcase %></h2>
      <span class="-ml-2 rounded-full border-2 border-white">
        <img class="h-12 w-12 rounded-full object-cover" src="<%= associate.url %>" alt="profile photo">
      </span>
    </div>

    <div class="flex justify-between">
      <% if associate.companies.count == 1%>
        <p class="text-sm font-medium text-gray-900 leading-snug"> <%= associate.companies.first.name %></p>
      <% else %>
      <ul>
        <% associate.companies.each do |company|  %>
        <li>
          <p class="text-sm font-medium text-gray-900 leading-snug"><%= company.name %></p>
        </li>
        <% end%>
      </ul>
      <% end%>
    </div>

    <div class="flex mt-2 justify-between items-baseline">
      <div class="text-sm text-gray-600">
        <p class="text-sm text-gray-600"> <%= associate.positions.first.title %></p>
      </div>

      <div>
        <span class="px-2 inline-flex items-center bg-teal-100 rounded">
          <svg class="h-2 w-2 text-teal-500" viewBox="0 0 8 8" fill="currentColor">
          <circle cx="4" cy="4" r="3" />
          </svg>
          <span class="ml-1 py-1 text-sm font-medium leading-tight text-teal-900"><%= associate.username %></span>
        </span>
      </div>
    </div>
  <% end %>
</li>